on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: yarn install --immutable

      - name: Deploy
        run: |
          git config --local user.email "yjj0287@gmail.com"
          git config --local user.name "Yeonju Jo"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
          yarn deploy
